import { useState, type ChangeEvent, type PointerEvent } from 'react'
import { acceptAttributeFor } from '@commietools/tools'
import { inspectPdf, type PdfInspection } from '@commietools/tools/pdf/core'
import { preflightPdfA, redactPdf, type PdfAPreflight } from '@commietools/tools/pdf/m9'
import { Button, LocalBadge } from '@commietools/ui'
import { SaveFileControl } from './SaveFileControl'
import { baseName, pdfErrorKey, useDownload, usePdfThumbnails, type Translate } from './pdfUi'

type Loaded = { name: string; bytes: Uint8Array; inspection: PdfInspection }
async function select(event: ChangeEvent<HTMLInputElement>): Promise<Loaded | null> { const file=event.target.files?.[0];event.target.value='';if(!file)return null;const bytes=new Uint8Array(await file.arrayBuffer());return{name:file.name,bytes,inspection:await inspectPdf(bytes)} }
function ErrorText({value,t}:{value:string;t:Translate}){return value?<p className="error" role="alert">{t(value)}</p>:null}
function Result({bytes,name,t}:{bytes:Uint8Array;name:string;t:Translate}){const url=useDownload(bytes);return url?<section className="settings-card stack"><div className="preview-heading"><h2>{t('tool.pdf.result')}</h2><LocalBadge>{t('status.local')}</LocalBadge></div><SaveFileControl url={url} suggestedName={name} mimeType="application/pdf" t={t}/></section>:null}

export function PdfAPreflightTool({t}:{t:Translate}){
  const [report,setReport]=useState<PdfAPreflight|null>(null),[error,setError]=useState('')
  async function choose(event:ChangeEvent<HTMLInputElement>){try{const file=await select(event);setReport(file?preflightPdfA(file.bytes):null);setError('')}catch(x){setReport(null);setError(pdfErrorKey(x))}}
  return <section className="settings-card stack"><label className="field"><span>{t('tool.pdf.choose')}</span><input type="file" accept={acceptAttributeFor('pdf-a-preflight')} onChange={choose}/></label><p className="warning">{t('tool.pdfA.limit')}</p>{report&&<><h2>{t(report.verdict==='not-declared'?'tool.pdfA.notDeclared':'tool.pdfA.declared')}</h2>{report.declaredPart&&<p>PDF/A-{report.declaredPart}{report.declaredConformance?.toLowerCase()}</p>}<dl className="results">{(['hasXmp','hasOutputIntent','hasEncryption','hasJavaScript','hasEmbeddedFiles'] as const).map(key=><div key={key}><dt>{t(`tool.pdfA.${key}`)}</dt><dd>{t(report[key]?'tool.pdfA.yes':'tool.pdfA.no')}</dd></div>)}</dl><p>{t('tool.pdfA.verapdf')}</p></>}<ErrorText value={error} t={t}/></section>
}

export function PdfRedactTool({t}:{t:Translate}){
  const [file,setFile]=useState<Loaded|null>(null),[page,setPage]=useState(1),[area,setArea]=useState<{x:number;y:number;width:number;height:number}|null>(null),[start,setStart]=useState<{x:number;y:number}|null>(null),[clearMetadata,setClearMetadata]=useState(true),[removeAnnotations,setRemoveAnnotations]=useState(true),[result,setResult]=useState<Uint8Array|null>(null),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false)
  const thumbs=usePdfThumbnails(file?.bytes??null,220)
  async function choose(event:ChangeEvent<HTMLInputElement>){try{setFile(await select(event));setPage(1);setArea(null);setResult(null);setConfirmed(false);setError('')}catch(e){setError(pdfErrorKey(e))}}
  function selectPage(next:number){setPage(next);setArea(null);setConfirmed(false)}
  function point(event:PointerEvent<HTMLDivElement>){const rect=event.currentTarget.getBoundingClientRect();return{x:Math.max(0,Math.min(rect.width,event.clientX-rect.left)),y:Math.max(0,Math.min(rect.height,event.clientY-rect.top)),rect}}
  function begin(event:PointerEvent<HTMLDivElement>){event.currentTarget.setPointerCapture(event.pointerId);const p=point(event);setStart({x:p.x,y:p.y});setArea(null);setConfirmed(false)}
  function finish(event:PointerEvent<HTMLDivElement>){if(!start||!file)return;const p=point(event),info=file.inspection.pages[page-1];if(!info)return;const x=Math.min(start.x,p.x),y=Math.min(start.y,p.y),width=Math.abs(p.x-start.x),height=Math.abs(p.y-start.y);setStart(null);if(width<4||height<4)return;setArea({x:x/p.rect.width*info.width,y:y/p.rect.height*info.height,width:width/p.rect.width*info.width,height:height/p.rect.height*info.height})}
  function run(){if(!file||!confirmed||!area)return;try{setResult(redactPdf(file.bytes,[{pageIndex:page-1,...area}],{clearMetadata,removePageAnnotations:removeAnnotations}));setError('')}catch(e){setError(pdfErrorKey(e))}}
  const info=file?.inspection.pages[page-1]
  return <div className="stack"><section className="settings-card stack"><label className="field"><span>{t('tool.pdf.choose')}</span><input type="file" accept={acceptAttributeFor('pdf-redact')} onChange={choose}/></label><p className="warning">{t('tool.pdfRedact.warning')}</p>{file&&<><div className="pdf-thumbnail-grid">{thumbs.images.map((image,index)=><button className={`pdf-page-card button-reset ${page===index+1?'selected':''}`} key={index} onClick={()=>selectPage(index+1)}><img src={image} alt={`${t('tool.pdf.page')} ${index+1}`}/><span>{index+1}</span></button>)}</div>{thumbs.images[page-1]&&info&&<div className="redaction-editor" onPointerDown={begin} onPointerUp={finish} role="img" aria-label={t('tool.pdfRedact.draw')}><img draggable="false" src={thumbs.images[page-1]} alt={`${t('tool.pdf.page')} ${page}`}/>{area&&<span className="redaction-box" style={{left:`${area.x/info.width*100}%`,top:`${area.y/info.height*100}%`,width:`${area.width/info.width*100}%`,height:`${area.height/info.height*100}%`}}/>}</div>}<p>{t('tool.pdfRedact.draw')}</p>{area&&<p>{t('tool.pdfRedact.selection').replace('{x}',area.x.toFixed(1)).replace('{y}',area.y.toFixed(1)).replace('{w}',area.width.toFixed(1)).replace('{h}',area.height.toFixed(1))}</p>}<label className="check-field"><input type="checkbox" checked={clearMetadata} onChange={e=>setClearMetadata(e.target.checked)}/>{t('tool.pdfRedact.clearMetadata')}</label><label className="check-field"><input type="checkbox" checked={removeAnnotations} onChange={e=>setRemoveAnnotations(e.target.checked)}/>{t('tool.pdfRedact.removeAnnotations')}</label><label className="check-field"><input type="checkbox" checked={confirmed} disabled={!area} onChange={e=>setConfirmed(e.target.checked)}/>{t('tool.pdfRedact.confirm')}</label><Button className="primary" disabled={!confirmed||!area} onClick={run}>{t('tool.pdfRedact.action')}</Button></>}<ErrorText value={error} t={t}/></section>{result&&file&&<Result bytes={result} name={`${baseName(file.name)}-redacted.pdf`} t={t}/>}</div>
}
