import { useState, type ChangeEvent } from 'react'
import { acceptAttributeFor } from '@commietools/tools'
import { inspectPdf, parsePageSelection, type PdfInspection } from '@commietools/tools/pdf/core'
import { addPdfAttachments, cleanPdfMetadata, comparePdfStructure, cropPdfPages, listPdfAttachments, readPdfMetadata, removePdfAttachment, renamePdfAttachment, repairAndValidatePdf, safeAttachmentName, type PdfAttachment, type PdfComparison, type PdfMetadata } from '@commietools/tools/pdf/m8'
import { Button, LocalBadge } from '@commietools/ui'
import { SaveFileControl } from './SaveFileControl'
import { baseName, comparePdfRendering, extractPdfText, pdfErrorKey, useDownload, type Translate } from './pdfUi'

type Loaded = { name: string; bytes: Uint8Array; inspection: PdfInspection }
async function selected(event: ChangeEvent<HTMLInputElement>): Promise<Loaded | null> { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return null; const bytes = new Uint8Array(await file.arrayBuffer()); return { name: file.name, bytes, inspection: await inspectPdf(bytes) } }
function Result({ bytes, name, t }: { bytes: Uint8Array; name: string; t: Translate }) { const url = useDownload(bytes); return url ? <section className="settings-card stack"><div className="preview-heading"><h2>{t('tool.pdf.result')}</h2><LocalBadge>{t('status.local')}</LocalBadge></div><SaveFileControl url={url} suggestedName={name} mimeType="application/pdf" t={t} /></section> : null }
function ErrorText({ error, t }: { error: string; t: Translate }) { return error ? <p className="error" role="alert">{t(error)}</p> : null }

export function PdfMetadataTool({ t }: { t: Translate }) {
  const [file, setFile] = useState<Loaded | null>(null), [metadata, setMetadata] = useState<PdfMetadata | null>(null), [result, setResult] = useState<Uint8Array | null>(null), [error, setError] = useState('')
  async function choose(e: ChangeEvent<HTMLInputElement>) { try { const next = await selected(e); setFile(next); setMetadata(next ? await readPdfMetadata(next.bytes) : null); setResult(null); setError('') } catch (x) { setError(pdfErrorKey(x)) } }
  async function clean() { if (!file) return; try { setResult(await cleanPdfMetadata(file.bytes)); setError('') } catch (x) { setError(pdfErrorKey(x)) } }
  return <div className="stack"><section className="settings-card stack"><label className="field"><span>{t('tool.pdf.choose')}</span><input type="file" accept={acceptAttributeFor('pdf-metadata')} onChange={choose} /></label><p className="privacy-note">{t('tool.pdf.local')}</p>{metadata && <dl className="results">{Object.entries(metadata).filter(([,v]) => v && (!Array.isArray(v) || v.length)).map(([key,value]) => <div key={key}><dt>{t(`tool.pdfMetadata.${key}`)}</dt><dd>{value instanceof Date ? value.toLocaleString() : Array.isArray(value) ? value.join(', ') : String(value)}</dd></div>)}</dl>}{file && <><p className="warning">{t('tool.pdfMetadata.scope')}</p><Button className="primary" onClick={clean}>{t('tool.pdfMetadata.clean')}</Button></>}<ErrorText error={error} t={t} /></section>{result && file && <Result bytes={result} name={`${baseName(file.name)}-metadata-cleaned.pdf`} t={t} />}</div>
}

export function PdfCropTool({ t }: { t: Translate }) {
  const [file,setFile]=useState<Loaded|null>(null), [pages,setPages]=useState(''), [margin,setMargin]=useState(20), [result,setResult]=useState<Uint8Array|null>(null), [error,setError]=useState('')
  async function choose(e:ChangeEvent<HTMLInputElement>){try{const n=await selected(e);setFile(n);setPages(n?`1-${n.inspection.pageCount}`:'');setResult(null);setError('')}catch(x){setError(pdfErrorKey(x))}}
  async function run(){if(!file)return;try{const chosen=parsePageSelection(pages,file.inspection.pageCount);setResult(await cropPdfPages(file.bytes,{pages:chosen,top:margin,right:margin,bottom:margin,left:margin}));setError('')}catch(x){setError(pdfErrorKey(x))}}
  return <div className="stack"><section className="settings-card stack"><label className="field"><span>{t('tool.pdf.choose')}</span><input type="file" accept={acceptAttributeFor('pdf-crop')} onChange={choose}/></label>{file&&<><label className="field"><span>{t('tool.pdfCrop.pages')}</span><input value={pages} onChange={e=>setPages(e.target.value)}/></label><label className="field"><span>{t('tool.pdfCrop.margin')}</span><input type="number" min="0" value={margin} onChange={e=>setMargin(Number(e.target.value))}/></label><p>{t('tool.pdfCrop.note')}</p><Button className="primary" onClick={run}>{t('tool.pdfCrop.action')}</Button></>}<ErrorText error={error} t={t}/></section>{result&&file&&<Result bytes={result} name={`${baseName(file.name)}-cropped.pdf`} t={t}/>}</div>
}

export function PdfRepairTool({ t }: { t: Translate }) {
  const [file,setFile]=useState<Loaded|null>(null),[result,setResult]=useState<Uint8Array|null>(null),[report,setReport]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  async function choose(e:ChangeEvent<HTMLInputElement>){try{setFile(await selected(e));setResult(null);setReport('');setError('')}catch(x){setError(pdfErrorKey(x))}}
  async function run(){if(!file)return;setBusy(true);try{const r=await repairAndValidatePdf(file.bytes);setResult(r.bytes);setReport(t(r.changed?'tool.pdfRepair.changed':'tool.pdfRepair.unchanged').replace('{pages}',String(r.pageCount)));setError('')}catch(x){setError(pdfErrorKey(x))}finally{setBusy(false)}}
  return <div className="stack"><section className="settings-card stack"><label className="field"><span>{t('tool.pdf.choose')}</span><input type="file" accept={acceptAttributeFor('pdf-repair')} onChange={choose}/></label><p className="warning">{t('tool.pdfRepair.scope')}</p>{file&&<Button className="primary" disabled={busy} onClick={run}>{busy?t('tool.pdf.processing'):t('tool.pdfRepair.action')}</Button>}{report&&<p className="success">{report}</p>}<ErrorText error={error} t={t}/></section>{result&&file&&<Result bytes={result} name={`${baseName(file.name)}-repaired.pdf`} t={t}/>}</div>
}

export function PdfAttachmentsTool({ t }: { t: Translate }) {
  const [file,setFile]=useState<Loaded|null>(null),[items,setItems]=useState<PdfAttachment[]>([]),[result,setResult]=useState<Uint8Array|null>(null),[error,setError]=useState('')
  async function choose(e:ChangeEvent<HTMLInputElement>){try{const n=await selected(e);setFile(n);setItems(n?await listPdfAttachments(n.bytes):[]);setResult(null);setError('')}catch(x){setError(pdfErrorKey(x))}}
  async function add(e:ChangeEvent<HTMLInputElement>){if(!file)return;try{const files=[...(e.target.files??[])];e.target.value='';const out=await addPdfAttachments(result??file.bytes,await Promise.all(files.map(async f=>({name:f.name,bytes:new Uint8Array(await f.arrayBuffer()),mimeType:f.type||undefined}))));setResult(out);setItems(await listPdfAttachments(out));setError('')}catch(x){setError(pdfErrorKey(x))}}
  async function remove(index:number){if(!file)return;try{const out=await removePdfAttachment(result??file.bytes,index);setResult(out);setItems(await listPdfAttachments(out));setError('')}catch(x){setError(pdfErrorKey(x))}}
  async function rename(item:PdfAttachment){if(!file)return;const requested=window.prompt(t('tool.pdfAttachments.renamePrompt'),item.name);if(!requested)return;try{const out=await renamePdfAttachment(result??file.bytes,item.index,requested);setResult(out);setItems(await listPdfAttachments(out));setError('')}catch(x){setError(pdfErrorKey(x))}}
  function download(item:PdfAttachment){const url=URL.createObjectURL(new Blob([new Uint8Array(item.bytes)]));const a=document.createElement('a');a.href=url;a.download=safeAttachmentName(item.name,`attachment-${item.index+1}`);a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  return <div className="stack"><section className="settings-card stack"><label className="field"><span>{t('tool.pdf.choose')}</span><input type="file" accept={acceptAttributeFor('pdf-attachments')} onChange={choose}/></label>{file&&<><p>{items.length?t('tool.pdfAttachments.found').replace('{count}',String(items.length)):t('tool.pdfAttachments.none')}</p>{items.map(item=><div className="preview-heading" key={item.index}><span>{item.name} · {item.size} B</span><span><Button onClick={()=>download(item)}>{t('tool.pdfAttachments.extract')}</Button> <Button onClick={()=>rename(item)}>{t('tool.pdfAttachments.rename')}</Button> <Button onClick={()=>remove(item.index)}>{t('tool.pdfAttachments.remove')}</Button></span></div>)}<label className="field"><span>{t('tool.pdfAttachments.add')}</span><input type="file" multiple onChange={add}/></label></>}<ErrorText error={error} t={t}/></section>{result&&file&&<Result bytes={result} name={`${baseName(file.name)}-attachments.pdf`} t={t}/>}</div>
}

export function PdfCompareTool({ t }: { t: Translate }) {
  const [files,setFiles]=useState<(Loaded|null)[]>([null,null]),[comparison,setComparison]=useState<(PdfComparison&{visual:readonly number[]})|null>(null),[tolerance,setTolerance]=useState(16),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  async function choose(index:number,e:ChangeEvent<HTMLInputElement>){try{const n=await selected(e);setFiles(old=>old.map((v,i)=>i===index?n:v));setComparison(null);setError('')}catch(x){setError(pdfErrorKey(x))}}
  async function run(){const [a,b]=files;if(!a||!b)return;setBusy(true);try{const [at,bt,visual]=await Promise.all([extractPdfText(a.bytes),extractPdfText(b.bytes),comparePdfRendering(a.bytes,b.bytes,tolerance)]);const shape=(f:Loaded,texts:typeof at)=>({pages:f.inspection.pages.map((p,i)=>({...p,text:texts[i]?.text??''}))});setComparison({...comparePdfStructure(shape(a,at),shape(b,bt)),visual});setError('')}catch(x){setError(pdfErrorKey(x))}finally{setBusy(false)}}
  return <section className="settings-card stack"><div className="form-grid">{[0,1].map(i=><label className="field" key={i}><span>{t(i?'tool.pdfCompare.right':'tool.pdfCompare.left')}</span><input type="file" accept={acceptAttributeFor('pdf-compare')} onChange={e=>choose(i,e)}/></label>)}</div><label className="field"><span>{t('tool.pdfCompare.tolerance')}</span><input type="range" min="0" max="64" value={tolerance} onChange={e=>setTolerance(Number(e.target.value))}/><output>{tolerance}</output></label><p>{t('tool.pdfCompare.scope')}</p><Button className="primary" disabled={busy||!files[0]||!files[1]} onClick={run}>{busy?t('tool.pdf.processing'):t('tool.pdfCompare.action')}</Button>{comparison&&<><p>{t(comparison.samePageCount?'tool.pdfCompare.sameCount':'tool.pdfCompare.differentCount')}</p><dl className="results">{comparison.pages.map((p,index)=><div key={p.page}><dt>{t('tool.pdf.page')} {p.page}</dt><dd>{[p.geometryEqual&&p.textEqual&&comparison.visual[index]===0?t('tool.pdfCompare.equal'):'',!p.geometryEqual?t('tool.pdfCompare.geometry'):'',!p.textEqual?t('tool.pdfCompare.text'):'',`${t('tool.pdfCompare.visual')}: ${((comparison.visual[index]??1)*100).toFixed(2)}%`].filter(Boolean).join(' · ')}</dd></div>)}</dl></>}<ErrorText error={error} t={t}/></section>
}
