[package]
name = "commietools-pdf-signer-wasm"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
pdf_signer = { git = "https://github.com/StrategicProjects/pdf_signer", rev = "6cc0218100d9ffc038f8dccee3b707e5bd136100" }
wasm-bindgen = "0.2"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
getrandom = { version = "0.2", features = ["js"] }
getrandom03 = { package = "getrandom", version = "0.3", features = ["wasm_js"] }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true

