// Generated by scripts/catalog-generate.mjs - do not edit by hand.
// Run `npm run catalog:generate` after changing manifests, locale catalogues or tool icons.

import type { ToolSearchEntry } from '@commietools/core'

export const toolIndex: readonly ToolSearchEntry[] = [
  {
    "id": "text-statistics",
    "route": "/tools/text-statistics",
    "icon": "/tools/text-statistics.svg",
    "category": "text",
    "suiteIds": [
      "text"
    ],
    "executionMode": "local",
    "resourceClass": "universal",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": [],
    "locales": {
      "de": {
        "title": "Textstatistik",
        "summary": "Zählt Zeichen, Wörter und Zeilen.",
        "terms": [
          "Text",
          "zählen",
          "Wörter",
          "Zeichen",
          "Zeilen",
          "Statistik",
          "Länge",
          "Umfang"
        ],
        "tags": [
          "#text"
        ]
      },
      "en": {
        "title": "Text statistics",
        "summary": "Counts characters, words and lines.",
        "terms": [
          "text",
          "count",
          "words",
          "characters",
          "lines",
          "statistics",
          "length",
          "size"
        ],
        "tags": [
          "#text"
        ]
      }
    }
  },
  {
    "id": "case-converter",
    "route": "/tools/case-converter",
    "icon": "/tools/case-converter.svg",
    "category": "text",
    "suiteIds": [
      "text"
    ],
    "executionMode": "local",
    "resourceClass": "universal",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": [],
    "locales": {
      "de": {
        "title": "Groß-/Kleinschreibung",
        "summary": "Ändert Groß- und Kleinschreibung.",
        "terms": [
          "Großschreibung",
          "Kleinschreibung",
          "Großbuchstaben",
          "Kleinbuchstaben",
          "Titelschreibung",
          "umwandeln",
          "Text"
        ],
        "tags": [
          "#text"
        ]
      },
      "en": {
        "title": "Letter case",
        "summary": "Changes letter case.",
        "terms": [
          "uppercase",
          "lowercase",
          "capitalize",
          "title case",
          "convert",
          "text"
        ],
        "tags": [
          "#text"
        ]
      }
    }
  },
  {
    "id": "json-formatter",
    "route": "/tools/json-formatter",
    "icon": "/tools/json-formatter.svg",
    "category": "developer",
    "suiteIds": [
      "developer"
    ],
    "executionMode": "local",
    "resourceClass": "universal",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": [],
    "locales": {
      "de": {
        "title": "JSON formatieren",
        "summary": "Rückt JSON ein und prüft es.",
        "terms": [
          "JSON",
          "formatieren",
          "einrücken",
          "verschönern",
          "prüfen",
          "validieren",
          "Fehler finden"
        ],
        "tags": [
          "#entwicklung"
        ]
      },
      "en": {
        "title": "Format JSON",
        "summary": "Indents and validates JSON.",
        "terms": [
          "json",
          "format",
          "pretty print",
          "indent",
          "validate",
          "check"
        ],
        "tags": [
          "#development"
        ]
      }
    }
  },
  {
    "id": "qr-code-generator",
    "route": "/tools/qr-code-generator",
    "icon": "/tools/qr-code-generator.svg",
    "category": "generator",
    "suiteIds": [
      "generators"
    ],
    "executionMode": "local",
    "resourceClass": "universal",
    "worksOffline": true,
    "input": [],
    "output": [
      "image/png",
      "image/svg+xml",
      "image/jpeg",
      "image/webp"
    ],
    "auxiliary": [
      {
        "role": "logo",
        "mimeTypes": [
          "image/png",
          "image/jpeg",
          "image/webp",
          "image/svg+xml"
        ]
      }
    ],
    "locales": {
      "de": {
        "title": "QR-Code-Generator",
        "summary": "Erzeugt QR-Codes als Bild.",
        "terms": [
          "QR-Code",
          "WLAN",
          "Zugang",
          "Visitenkarte",
          "vCard",
          "Link",
          "Adresse",
          "E-Mail",
          "erzeugen"
        ],
        "tags": [
          "#generator"
        ]
      },
      "en": {
        "title": "QR code generator",
        "summary": "Creates QR codes as an image.",
        "terms": [
          "qr code",
          "wifi",
          "access",
          "vcard",
          "contact",
          "link",
          "url",
          "email",
          "generate"
        ],
        "tags": [
          "#generator"
        ]
      }
    }
  },
  {
    "id": "image-metadata",
    "route": "/tools/image-metadata",
    "icon": "/tools/image-metadata.svg",
    "category": "image",
    "suiteIds": [
      "image"
    ],
    "executionMode": "local",
    "resourceClass": "universal",
    "worksOffline": true,
    "input": [
      "image/jpeg",
      "image/png",
      "image/webp",
      "image/gif",
      "image/bmp",
      "image/tiff",
      "image/avif",
      "image/heic"
    ],
    "output": [
      "image/jpeg",
      "image/png",
      "image/webp"
    ],
    "auxiliary": [],
    "locales": {
      "de": {
        "title": "Bild-Metadaten",
        "summary": "Zeigt und entfernt versteckte Bilddaten.",
        "terms": [
          "Metadaten",
          "EXIF",
          "GPS",
          "Standort",
          "Ortsdaten",
          "entfernen",
          "löschen",
          "Foto",
          "Handyfoto",
          "Privatsphäre",
          "Datenschutz"
        ],
        "tags": [
          "#datenschutz",
          "#bilder"
        ]
      },
      "en": {
        "title": "Image metadata",
        "summary": "Shows and removes hidden image data.",
        "terms": [
          "metadata",
          "exif",
          "gps",
          "location",
          "remove",
          "strip",
          "photo",
          "picture",
          "privacy"
        ],
        "tags": [
          "#privacy",
          "#images"
        ]
      }
    }
  },
  {
    "id": "image-resize",
    "route": "/tools/image-resize",
    "icon": "/tools/image-resize.svg",
    "category": "image",
    "suiteIds": [
      "image"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [
      "image/jpeg",
      "image/png",
      "image/webp"
    ],
    "output": [
      "image/jpeg",
      "image/png",
      "image/webp"
    ],
    "auxiliary": [],
    "locales": {
      "de": {
        "title": "Bild skalieren",
        "summary": "Ändert Größe, Zuschnitt und Ausrichtung.",
        "terms": [
          "skalieren",
          "verkleinern",
          "vergrößern",
          "Bildgröße",
          "Zuschnitt",
          "zuschneiden",
          "drehen",
          "spiegeln",
          "Foto",
          "Profilbild"
        ],
        "tags": [
          "#bilder"
        ]
      },
      "en": {
        "title": "Resize image",
        "summary": "Changes size, crop and orientation.",
        "terms": [
          "resize",
          "scale",
          "shrink",
          "enlarge",
          "image size",
          "crop",
          "rotate",
          "mirror",
          "photo",
          "profile picture"
        ],
        "tags": [
          "#images"
        ]
      }
    }
  }
]
