// Generated by scripts/catalog-generate.mjs - do not edit by hand.
// Run `npm run catalog:generate` after changing manifests, locale catalogues or tool icons.

import type { ToolCatalogEntry } from '@commietools/core'

export const toolIndex: readonly ToolCatalogEntry[] = [
  {
    "id": "text-statistics",
    "route": "/tools/text-statistics",
    "icon": "/tools/text-statistics.svg",
    "category": "text",
    "suiteIds": [
      "text"
    ],
    "executionMode": "local",
    "resourceClass": "universal",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": []
  },
  {
    "id": "case-converter",
    "route": "/tools/case-converter",
    "icon": "/tools/case-converter.svg",
    "category": "text",
    "suiteIds": [
      "text"
    ],
    "executionMode": "local",
    "resourceClass": "universal",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": []
  },
  {
    "id": "json-formatter",
    "route": "/tools/json-formatter",
    "icon": "/tools/json-formatter.svg",
    "category": "developer",
    "suiteIds": [
      "developer"
    ],
    "executionMode": "local",
    "resourceClass": "universal",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": []
  },
  {
    "id": "qr-code-generator",
    "route": "/tools/qr-code-generator",
    "icon": "/tools/qr-code-generator.svg",
    "category": "generator",
    "suiteIds": [
      "generators"
    ],
    "executionMode": "local",
    "resourceClass": "universal",
    "worksOffline": true,
    "input": [],
    "output": [
      "image/png",
      "image/svg+xml",
      "image/jpeg",
      "image/webp"
    ],
    "auxiliary": [
      {
        "role": "logo",
        "mimeTypes": [
          "image/png",
          "image/jpeg",
          "image/webp",
          "image/svg+xml"
        ]
      }
    ]
  },
  {
    "id": "image-metadata",
    "route": "/tools/image-metadata",
    "icon": "/tools/image-metadata.svg",
    "category": "image",
    "suiteIds": [
      "image"
    ],
    "executionMode": "local",
    "resourceClass": "universal",
    "worksOffline": true,
    "input": [
      "image/jpeg",
      "image/png",
      "image/webp",
      "image/gif",
      "image/bmp",
      "image/tiff",
      "image/avif",
      "image/heic"
    ],
    "output": [
      "image/jpeg",
      "image/png",
      "image/webp"
    ],
    "auxiliary": []
  },
  {
    "id": "image-resize",
    "route": "/tools/image-resize",
    "icon": "/tools/image-resize.svg",
    "category": "image",
    "suiteIds": [
      "image"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [
      "image/jpeg",
      "image/png",
      "image/webp"
    ],
    "output": [
      "image/jpeg",
      "image/png",
      "image/webp"
    ],
    "auxiliary": []
  },
  {
    "id": "icon-generator",
    "route": "/tools/icon-generator",
    "icon": "/tools/icon-generator.svg",
    "category": "image",
    "suiteIds": [
      "image"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [
      "image/png",
      "image/jpeg",
      "image/webp"
    ],
    "output": [
      "image/png",
      "image/x-icon"
    ],
    "auxiliary": []
  },
  {
    "id": "image-watermark",
    "route": "/tools/image-watermark",
    "icon": "/tools/image-watermark.svg",
    "category": "image",
    "suiteIds": [
      "image"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [
      "image/jpeg",
      "image/png",
      "image/webp"
    ],
    "output": [
      "image/jpeg",
      "image/png",
      "image/webp"
    ],
    "auxiliary": [
      {
        "role": "logo",
        "mimeTypes": [
          "image/png",
          "image/jpeg",
          "image/webp"
        ]
      }
    ]
  },
  {
    "id": "color-tools",
    "route": "/tools/color-tools",
    "icon": "/tools/color-tools.svg",
    "category": "image",
    "suiteIds": [
      "image"
    ],
    "executionMode": "local",
    "resourceClass": "universal",
    "worksOffline": true,
    "input": [
      "image/jpeg",
      "image/png",
      "image/webp"
    ],
    "output": [],
    "auxiliary": []
  },
  {
    "id": "pdf-merge",
    "route": "/tools/pdf-merge",
    "icon": "/tools/pdf-merge.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": []
  },
  {
    "id": "pdf-split",
    "route": "/tools/pdf-split",
    "icon": "/tools/pdf-split.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": []
  },
  {
    "id": "pdf-organize",
    "route": "/tools/pdf-organize",
    "icon": "/tools/pdf-organize.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": []
  },
  {
    "id": "images-to-pdf",
    "route": "/tools/images-to-pdf",
    "icon": "/tools/images-to-pdf.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [
      "image/jpeg",
      "image/png"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": []
  },
  {
    "id": "pdf-to-images",
    "route": "/tools/pdf-to-images",
    "icon": "/tools/pdf-to-images.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "heavy",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "image/png",
      "image/jpeg"
    ],
    "auxiliary": []
  },
  {
    "id": "pdf-watermark",
    "route": "/tools/pdf-watermark",
    "icon": "/tools/pdf-watermark.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": []
  },
  {
    "id": "pdf-page-numbers",
    "route": "/tools/pdf-page-numbers",
    "icon": "/tools/pdf-page-numbers.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": []
  },
  {
    "id": "pdf-visible-signature",
    "route": "/tools/pdf-visible-signature",
    "icon": "/tools/pdf-visible-signature.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": [
      {
        "role": "signature",
        "mimeTypes": [
          "image/png",
          "image/jpeg"
        ]
      }
    ]
  },
  {
    "id": "pdf-form-fill",
    "route": "/tools/pdf-form-fill",
    "icon": "/tools/pdf-form-fill.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "heavy",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": []
  },
  {
    "id": "pdf-annotate",
    "route": "/tools/pdf-annotate",
    "icon": "/tools/pdf-annotate.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "heavy",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": []
  },
  {
    "id": "pdf-security",
    "route": "/tools/pdf-security",
    "icon": "/tools/pdf-security.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "heavy",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": []
  },
  {
    "id": "pdf-compress",
    "route": "/tools/pdf-compress",
    "icon": "/tools/pdf-compress.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "heavy",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": []
  },
  {
    "id": "pdf-viewer",
    "route": "/tools/pdf-viewer",
    "icon": "/tools/pdf-viewer.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "heavy",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [],
    "auxiliary": []
  },
  {
    "id": "pdf-text-ocr",
    "route": "/tools/pdf-text-ocr",
    "icon": "/tools/pdf-text-ocr.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "heavy",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "text/plain"
    ],
    "auxiliary": []
  },
  {
    "id": "pdf-certificate-sign",
    "route": "/tools/pdf-certificate-sign",
    "icon": "/tools/pdf-certificate-sign.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "heavy",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": [
      {
        "role": "certificate",
        "mimeTypes": [
          "application/x-pkcs12"
        ]
      }
    ]
  },
  {
    "id": "pdf-signature-verify",
    "route": "/tools/pdf-signature-verify",
    "icon": "/tools/pdf-signature-verify.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "heavy",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [],
    "auxiliary": []
  },
  {
    "id": "pdf-metadata",
    "route": "/tools/pdf-metadata",
    "icon": "/tools/pdf-metadata.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": []
  },
  {
    "id": "pdf-crop",
    "route": "/tools/pdf-crop",
    "icon": "/tools/pdf-crop.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": []
  },
  {
    "id": "pdf-repair",
    "route": "/tools/pdf-repair",
    "icon": "/tools/pdf-repair.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "heavy",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": []
  },
  {
    "id": "pdf-attachments",
    "route": "/tools/pdf-attachments",
    "icon": "/tools/pdf-attachments.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": []
  },
  {
    "id": "pdf-compare",
    "route": "/tools/pdf-compare",
    "icon": "/tools/pdf-compare.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "heavy",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [],
    "auxiliary": []
  },
  {
    "id": "pdf-a-preflight",
    "route": "/tools/pdf-a-preflight",
    "icon": "/tools/pdf-a-preflight.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [],
    "auxiliary": []
  },
  {
    "id": "pdf-redact",
    "route": "/tools/pdf-redact",
    "icon": "/tools/pdf-redact.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "heavy",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": []
  },
  {
    "id": "calculator",
    "route": "/tools/calculator",
    "icon": "/tools/calculator.svg",
    "category": "calculator",
    "suiteIds": [
      "calculator"
    ],
    "executionMode": "local",
    "resourceClass": "heavy",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": []
  },
  {
    "id": "scientific-calculator",
    "route": "/tools/scientific-calculator",
    "icon": "/tools/scientific-calculator.svg",
    "category": "calculator",
    "suiteIds": [
      "calculator"
    ],
    "executionMode": "local",
    "resourceClass": "heavy",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": []
  },
  {
    "id": "programmer-calculator",
    "route": "/tools/programmer-calculator",
    "icon": "/tools/programmer-calculator.svg",
    "category": "calculator",
    "suiteIds": [
      "calculator"
    ],
    "executionMode": "local",
    "resourceClass": "heavy",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": []
  },
  {
    "id": "rpn-calculator",
    "route": "/tools/rpn-calculator",
    "icon": "/tools/rpn-calculator.svg",
    "category": "calculator",
    "suiteIds": [
      "calculator"
    ],
    "executionMode": "local",
    "resourceClass": "heavy",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": []
  },
  {
    "id": "commercial",
    "route": "/tools/commercial",
    "icon": "/tools/commercial.svg",
    "category": "calculator",
    "suiteIds": [
      "calculator"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": []
  },
  {
    "id": "convert",
    "route": "/tools/convert",
    "icon": "/tools/convert.svg",
    "category": "calculator",
    "suiteIds": [
      "calculator"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": []
  },
  {
    "id": "datetime",
    "route": "/tools/datetime",
    "icon": "/tools/datetime.svg",
    "category": "calculator",
    "suiteIds": [
      "calculator"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": []
  },
  {
    "id": "plotter",
    "route": "/tools/plotter",
    "icon": "/tools/plotter.svg",
    "category": "calculator",
    "suiteIds": [
      "calculator"
    ],
    "executionMode": "local",
    "resourceClass": "heavy",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": []
  },
  {
    "id": "aufmass",
    "route": "/tools/aufmass",
    "icon": "/tools/aufmass.svg",
    "category": "calculator",
    "suiteIds": [
      "calculator"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [],
    "output": [
      "text/csv",
      "application/pdf",
      "text/plain"
    ],
    "auxiliary": []
  },
  {
    "id": "statistics",
    "route": "/tools/statistics",
    "icon": "/tools/statistics.svg",
    "category": "calculator",
    "suiteIds": [
      "calculator"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": []
  },
  {
    "id": "equations",
    "route": "/tools/equations",
    "icon": "/tools/equations.svg",
    "category": "calculator",
    "suiteIds": [
      "calculator"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": []
  },
  {
    "id": "geometry",
    "route": "/tools/geometry",
    "icon": "/tools/geometry.svg",
    "category": "calculator",
    "suiteIds": [
      "calculator"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": []
  },
  {
    "id": "concrete",
    "route": "/tools/concrete",
    "icon": "/tools/concrete.svg",
    "category": "craft",
    "suiteIds": [
      "craft"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": []
  },
  {
    "id": "roof",
    "route": "/tools/roof",
    "icon": "/tools/roof.svg",
    "category": "craft",
    "suiteIds": [
      "craft"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": []
  },
  {
    "id": "metal-weight",
    "route": "/tools/metal-weight",
    "icon": "/tools/metal-weight.svg",
    "category": "craft",
    "suiteIds": [
      "craft"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": []
  },
  {
    "id": "wood",
    "route": "/tools/wood",
    "icon": "/tools/wood.svg",
    "category": "craft",
    "suiteIds": [
      "craft"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": []
  },
  {
    "id": "tiles",
    "route": "/tools/tiles",
    "icon": "/tools/tiles.svg",
    "category": "craft",
    "suiteIds": [
      "craft"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": []
  },
  {
    "id": "paint",
    "route": "/tools/paint",
    "icon": "/tools/paint.svg",
    "category": "craft",
    "suiteIds": [
      "craft"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": []
  },
  {
    "id": "drywall",
    "route": "/tools/drywall",
    "icon": "/tools/drywall.svg",
    "category": "craft",
    "suiteIds": [
      "craft"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": []
  }
]
