// Generated by scripts/catalog-generate.mjs - do not edit by hand.
// Run `npm run catalog:generate` after changing manifests, locale catalogues or tool icons.

import type { ToolSearchEntry } from '@commietools/core'

export const toolIndex: readonly ToolSearchEntry[] = [
  {
    "id": "text-statistics",
    "route": "/tools/text-statistics",
    "icon": "/tools/text-statistics.svg",
    "category": "text",
    "suiteIds": [
      "text"
    ],
    "executionMode": "local",
    "resourceClass": "universal",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": [],
    "locales": {
      "de": {
        "title": "Textstatistik",
        "summary": "Zählt Zeichen, Wörter und Zeilen.",
        "description": "Zählt Zeichen, Wörter und Zeilen direkt im Browser.",
        "terms": [
          "Text",
          "zählen",
          "zaehlen",
          "auszählen",
          "Wörter",
          "Woerter",
          "Wortzahl",
          "Wortanzahl",
          "Zeichen",
          "Zeichenzahl",
          "Zeichenanzahl",
          "Buchstaben",
          "Buchstabenzahl",
          "Zeilen",
          "Zeilenanzahl",
          "Absätze",
          "Absaetze",
          "Statistik",
          "Textstatistik",
          "Textlänge",
          "Textlaenge",
          "Länge",
          "Laenge",
          "Umfang",
          "Größe",
          "Groesse",
          "Anzahl",
          "Analyse",
          "Textanalyse",
          "Zählung",
          "Dokument",
          "Wort",
          "Zeile"
        ],
        "tags": [
          "#text"
        ]
      },
      "en": {
        "title": "Text statistics",
        "summary": "Counts characters, words and lines.",
        "description": "Counts characters, words and lines in your browser.",
        "terms": [
          "text",
          "count",
          "counting",
          "counter",
          "tally",
          "word",
          "words",
          "word count",
          "word number",
          "character",
          "characters",
          "character count",
          "letter",
          "letters",
          "line",
          "lines",
          "line count",
          "paragraph",
          "paragraphs",
          "statistics",
          "stats",
          "text statistics",
          "text length",
          "length",
          "size",
          "number",
          "analysis",
          "analyse",
          "analyze",
          "document"
        ],
        "tags": [
          "#text"
        ]
      }
    }
  },
  {
    "id": "case-converter",
    "route": "/tools/case-converter",
    "icon": "/tools/case-converter.svg",
    "category": "text",
    "suiteIds": [
      "text"
    ],
    "executionMode": "local",
    "resourceClass": "universal",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": [],
    "locales": {
      "de": {
        "title": "Groß-/Kleinschreibung",
        "summary": "Ändert Groß- und Kleinschreibung.",
        "description": "Wandelt Text lokal in Groß-, Klein- oder Titelschreibung um.",
        "terms": [
          "Großschreibung",
          "Grossschreibung",
          "Großbuchstaben",
          "Grossbuchstaben",
          "Kleinschreibung",
          "Kleinbuchstaben",
          "Groß- und Kleinschreibung",
          "Großschrift",
          "Kleinschrift",
          "Titelschreibung",
          "Titel",
          "Überschrift",
          "Schreibweise",
          "Versalien",
          "Kapitalisierung",
          "umwandeln",
          "umformen",
          "umstellen",
          "konvertieren",
          "ändern",
          "aendern",
          "anpassen",
          "Text",
          "Buchstaben",
          "Wort",
          "Wörter",
          "Satz",
          "Textblock",
          "Groß",
          "Gross",
          "klein",
          "Satzanfang"
        ],
        "tags": [
          "#text",
          "#schreibweise"
        ]
      },
      "en": {
        "title": "Letter case",
        "summary": "Changes letter case.",
        "description": "Converts text locally to upper, lower or title case.",
        "terms": [
          "uppercase",
          "upper case",
          "lowercase",
          "lower case",
          "capital letters",
          "capitalise",
          "capitalize",
          "capitalisation",
          "capitalization",
          "title case",
          "headline",
          "letter case",
          "casing",
          "case",
          "convert",
          "conversion",
          "change",
          "transform",
          "switch",
          "text",
          "letters",
          "words",
          "sentence",
          "paragraph",
          "all caps"
        ],
        "tags": [
          "#text",
          "#casing"
        ]
      }
    }
  },
  {
    "id": "json-formatter",
    "route": "/tools/json-formatter",
    "icon": "/tools/json-formatter.svg",
    "category": "developer",
    "suiteIds": [
      "developer"
    ],
    "executionMode": "local",
    "resourceClass": "universal",
    "worksOffline": true,
    "input": [],
    "output": [],
    "auxiliary": [],
    "locales": {
      "de": {
        "title": "JSON formatieren",
        "summary": "Rückt JSON ein und prüft es.",
        "description": "Prüft und formatiert JSON vollständig im Browser.",
        "terms": [
          "JSON",
          "JSON-Daten",
          "JSON-Formatierer",
          "formatieren",
          "formatiert",
          "Formatierung",
          "einrücken",
          "einruecken",
          "Einrückung",
          "verschönern",
          "verschoenern",
          "aufhübschen",
          "lesbar",
          "übersichtlich",
          "uebersichtlich",
          "prüfen",
          "pruefen",
          "überprüfen",
          "ueberpruefen",
          "validieren",
          "Validierung",
          "Gültigkeit",
          "gueltigkeit",
          "Fehler",
          "Fehler finden",
          "Fehlersuche",
          "Syntax",
          "Syntaxfehler",
          "Struktur",
          "strukturieren",
          "Leerzeichen",
          "Einzug",
          "Datei",
          "Konfiguration",
          "Daten",
          "Entwicklung",
          "Programmierung"
        ],
        "tags": [
          "#entwicklung",
          "#json",
          "#daten"
        ]
      },
      "en": {
        "title": "Format JSON",
        "summary": "Indents and validates JSON.",
        "description": "Validates and formats JSON entirely in your browser.",
        "terms": [
          "json",
          "json data",
          "json formatter",
          "json viewer",
          "format",
          "formatter",
          "formatting",
          "prettify",
          "pretty",
          "pretty print",
          "beautify",
          "indent",
          "indentation",
          "readable",
          "validate",
          "validation",
          "check",
          "verify",
          "error",
          "errors",
          "error message",
          "syntax",
          "syntax error",
          "structure",
          "parse",
          "parsing",
          "whitespace",
          "spaces",
          "file",
          "config",
          "data",
          "developer",
          "development",
          "programming"
        ],
        "tags": [
          "#development",
          "#json",
          "#data"
        ]
      }
    }
  },
  {
    "id": "qr-code-generator",
    "route": "/tools/qr-code-generator",
    "icon": "/tools/qr-code-generator.svg",
    "category": "generator",
    "suiteIds": [
      "generators"
    ],
    "executionMode": "local",
    "resourceClass": "universal",
    "worksOffline": true,
    "input": [],
    "output": [
      "image/png",
      "image/svg+xml",
      "image/jpeg",
      "image/webp"
    ],
    "auxiliary": [
      {
        "role": "logo",
        "mimeTypes": [
          "image/png",
          "image/jpeg",
          "image/webp",
          "image/svg+xml"
        ]
      }
    ],
    "locales": {
      "de": {
        "title": "QR-Code-Generator",
        "summary": "Erzeugt QR-Codes als Bild.",
        "description": "Erstellt vielseitige, gestaltbare QR-Codes vollständig auf deinem Gerät.",
        "terms": [
          "QR-Code",
          "QR",
          "QRCode",
          "QRCodes",
          "Code",
          "WLAN",
          "WiFi",
          "Wi-Fi",
          "Funknetz",
          "Zugang",
          "Zugangsdaten",
          "Netzwerk",
          "Passwort",
          "Kennwort",
          "Router",
          "Visitenkarte",
          "Kontakt",
          "vCard",
          "Adresse",
          "Anschrift",
          "Link",
          "URL",
          "Webadresse",
          "Website",
          "Homepage",
          "E-Mail",
          "Email",
          "Mail",
          "Telefon",
          "Telefonnummer",
          "SMS",
          "Nachricht",
          "Text",
          "Koordinaten",
          "Standort",
          "Geo",
          "Geodaten",
          "erzeugen",
          "erstellen",
          "generieren",
          "Generator",
          "herstellen",
          "Bild",
          "PNG",
          "SVG",
          "Grafik",
          "Logo",
          "Farbe",
          "Farben",
          "Stil",
          "Design",
          "Format",
          "drucken",
          "Druck",
          "Aufkleber",
          "Plakat",
          "scannen",
          "Scan",
          "Mobile",
          "Handy"
        ],
        "tags": [
          "#generator",
          "#qr",
          "#kontakt",
          "#wlan"
        ]
      },
      "en": {
        "title": "QR code generator",
        "summary": "Creates QR codes as an image.",
        "description": "Creates versatile, customizable QR codes entirely on your device.",
        "terms": [
          "qr",
          "qr code",
          "qrcode",
          "qr codes",
          "code",
          "wifi",
          "wi-fi",
          "wireless",
          "network",
          "access",
          "credentials",
          "password",
          "router",
          "vcard",
          "contact",
          "business card",
          "address",
          "link",
          "url",
          "web address",
          "website",
          "email",
          "mail",
          "phone",
          "telephone",
          "telephone number",
          "sms",
          "message",
          "text",
          "coordinates",
          "location",
          "geo",
          "geodata",
          "generate",
          "generator",
          "create",
          "make",
          "image",
          "png",
          "svg",
          "graphic",
          "logo",
          "colour",
          "color",
          "style",
          "design",
          "format",
          "print",
          "printing",
          "sticker",
          "poster",
          "scan",
          "scanning",
          "mobile",
          "smartphone"
        ],
        "tags": [
          "#generator",
          "#qr",
          "#contact",
          "#wifi"
        ]
      }
    }
  },
  {
    "id": "image-metadata",
    "route": "/tools/image-metadata",
    "icon": "/tools/image-metadata.svg",
    "category": "image",
    "suiteIds": [
      "image"
    ],
    "executionMode": "local",
    "resourceClass": "universal",
    "worksOffline": true,
    "input": [
      "image/jpeg",
      "image/png",
      "image/webp",
      "image/gif",
      "image/bmp",
      "image/tiff",
      "image/avif",
      "image/heic"
    ],
    "output": [
      "image/jpeg",
      "image/png",
      "image/webp"
    ],
    "auxiliary": [],
    "locales": {
      "de": {
        "title": "Bild-Metadaten",
        "summary": "Zeigt und entfernt versteckte Bilddaten.",
        "description": "Zeigt versteckte Metadaten in Fotos und entfernt sie, ohne das Bild neu zu berechnen.",
        "terms": [
          "Metadaten",
          "Bilddaten",
          "Bildinformationen",
          "Informationen",
          "EXIF",
          "EXIF-Daten",
          "GPS",
          "Standort",
          "Ortsdaten",
          "Geodaten",
          "Koordinaten",
          "Position",
          "Aufnahmeort",
          "Kamera",
          "Handykamera",
          "Smartphone",
          "Aufnahmedatum",
          "Aufnahmezeit",
          "Datum",
          "Uhrzeit",
          "Zeitstempel",
          "Belichtung",
          "Belichtungszeit",
          "Blende",
          "ISO",
          "Brennweite",
          "Objektiv",
          "Blitz",
          "Seriennummer",
          "Gerät",
          "Kameramodell",
          "Copyright",
          "Urheber",
          "Künstler",
          "Kuenstler",
          "Fotograf",
          "Autor",
          "Software",
          "Programm",
          "Kommentar",
          "Beschreibung",
          "Schlagwörter",
          "XMP",
          "IPTC",
          "ICC",
          "Farbprofil",
          "Ausrichtung",
          "Drehung",
          "entfernen",
          "löschen",
          "loeschen",
          "bereinigen",
          "säubern",
          "saeubern",
          "anonymisieren",
          "versteckte Daten",
          "Verlauf",
          "Spuren",
          "Tracking",
          "verlustfrei",
          "ohne Neuberechnung",
          "Privatsphäre",
          "Privatsphaere",
          "Datenschutz",
          "Foto",
          "Bild",
          "Handyfoto",
          "Bilddatei",
          "JPEG",
          "PNG",
          "WebP",
          "teilen",
          "veröffentlichen",
          "veroeffentlichen",
          "verschicken"
        ],
        "tags": [
          "#datenschutz",
          "#bilder",
          "#exif",
          "#gps",
          "#privatsphäre"
        ]
      },
      "en": {
        "title": "Image metadata",
        "summary": "Shows and removes hidden image data.",
        "description": "Shows hidden metadata in photos and removes it without re-encoding the image.",
        "terms": [
          "metadata",
          "exif",
          "image data",
          "image information",
          "information",
          "exif data",
          "gps",
          "location",
          "geodata",
          "geo",
          "coordinates",
          "position",
          "capture location",
          "camera",
          "phone camera",
          "smartphone",
          "capture date",
          "capture time",
          "date",
          "time",
          "timestamp",
          "exposure",
          "exposure time",
          "aperture",
          "iso",
          "focal length",
          "lens",
          "flash",
          "serial number",
          "device",
          "camera model",
          "copyright",
          "creator",
          "artist",
          "photographer",
          "author",
          "software",
          "program",
          "comment",
          "description",
          "keywords",
          "xmp",
          "iptc",
          "icc",
          "colour profile",
          "color profile",
          "orientation",
          "rotation",
          "remove",
          "delete",
          "strip",
          "clean",
          "cleanse",
          "sanitise",
          "sanitize",
          "anonymise",
          "anonymize",
          "hidden data",
          "trail",
          "traces",
          "tracking",
          "lossless",
          "without re-encoding",
          "privacy",
          "photo",
          "picture",
          "image",
          "image file",
          "jpeg",
          "png",
          "webp",
          "share",
          "publish",
          "send"
        ],
        "tags": [
          "#privacy",
          "#images",
          "#exif",
          "#gps"
        ]
      }
    }
  },
  {
    "id": "image-resize",
    "route": "/tools/image-resize",
    "icon": "/tools/image-resize.svg",
    "category": "image",
    "suiteIds": [
      "image"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [
      "image/jpeg",
      "image/png",
      "image/webp"
    ],
    "output": [
      "image/jpeg",
      "image/png",
      "image/webp"
    ],
    "auxiliary": [],
    "locales": {
      "de": {
        "title": "Bild skalieren",
        "summary": "Ändert Größe, Zuschnitt und Ausrichtung.",
        "description": "Verkleinert, vergrößert, dreht, spiegelt und schneidet Bilder zu – vollständig auf deinem Gerät.",
        "terms": [
          "skalieren",
          "Skalierung",
          "verkleinern",
          "Verkleinerung",
          "verkleinert",
          "vergrößern",
          "vergroessern",
          "Vergrößerung",
          "Größe ändern",
          "Groesse aendern",
          "Bildgröße ändern",
          "Bildgroesse aendern",
          "Größe",
          "Groesse",
          "Abmessungen",
          "Pixel",
          "Pixelmaße",
          "Pixelmasse",
          "Breite",
          "Höhe",
          "Auflösung",
          "Aufloesung",
          "Zuschnitt",
          "zuschneiden",
          "beschneiden",
          "ausschneiden",
          "Crop",
          "Ausschnitt",
          "drehen",
          "Drehung",
          "Rotation",
          "rotieren",
          "um 90 Grad drehen",
          "spiegeln",
          "Spiegelung",
          "horizontal spiegeln",
          "vertikal spiegeln",
          "Ausrichtung",
          "Seitenverhältnis",
          "Seitenverhaeltnis",
          "proportional",
          "Proportionen erhalten",
          "Quadrat",
          "quadratisch",
          "Profilbild",
          "Avatar",
          "Vorschaubild",
          "Thumbnail",
          "Vorschau",
          "Webseite",
          "Social Media",
          "Instagram",
          "Facebook",
          "WhatsApp",
          "E-Mail-Anhang",
          "Anhang",
          "Foto",
          "Bild",
          "Handyfoto",
          "Bilddatei",
          "JPEG",
          "PNG",
          "WebP",
          "zuschneiden auf Quadrat",
          "Bild verkleinern für E-Mail"
        ],
        "tags": [
          "#bilder",
          "#größe",
          "#zuschnitt",
          "#drehen",
          "#profilbild"
        ]
      },
      "en": {
        "title": "Resize image",
        "summary": "Changes size, crop and orientation.",
        "description": "Shrinks, enlarges, rotates, mirrors and crops images – entirely on your device.",
        "terms": [
          "resize",
          "resizing",
          "resize image",
          "scale",
          "scaling",
          "shrink",
          "shrink image",
          "make smaller",
          "reduce",
          "enlarge",
          "enlarge image",
          "make bigger",
          "increase",
          "change size",
          "image size",
          "size",
          "dimensions",
          "pixels",
          "width",
          "height",
          "resolution",
          "crop",
          "cropping",
          "cut",
          "cut out",
          "trim",
          "aspect",
          "rotate",
          "rotation",
          "turn",
          "rotate 90 degrees",
          "mirror",
          "mirroring",
          "flip",
          "flip horizontal",
          "flip vertical",
          "orientation",
          "aspect ratio",
          "proportional",
          "keep proportions",
          "square",
          "square crop",
          "profile picture",
          "avatar",
          "profile photo",
          "thumbnail",
          "preview",
          "website",
          "social media",
          "instagram",
          "facebook",
          "whatsapp",
          "email attachment",
          "attachment",
          "photo",
          "picture",
          "image",
          "image file",
          "jpeg",
          "png",
          "webp"
        ],
        "tags": [
          "#images",
          "#size",
          "#crop",
          "#rotate",
          "#avatar"
        ]
      }
    }
  },
  {
    "id": "icon-generator",
    "route": "/tools/icon-generator",
    "icon": "/tools/icon-generator.svg",
    "category": "image",
    "suiteIds": [
      "image"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [
      "image/png",
      "image/jpeg",
      "image/webp"
    ],
    "output": [
      "image/png",
      "image/x-icon"
    ],
    "auxiliary": [],
    "locales": {
      "de": {
        "title": "Icon-Generator",
        "summary": "Erzeugt Favicon- und Icon-Sätze aus einem Bild.",
        "description": "Erzeugt aus einem Bild einen vollständigen Satz Symbole: Favicon, PWA-Icons, Apple-Touch-Icon und eine maskierbare Variante – vollständig auf deinem Gerät.",
        "terms": [
          "icon",
          "icons",
          "favicon",
          "favicon.ico",
          "app icon",
          "App-Symbol",
          "Symbol",
          "Symbole",
          "Website-Icon",
          "Webseite",
          "Icon-Satz",
          "Icon-Set",
          "Icongrößen",
          "Icongroessen",
          "Größen",
          "Groessen",
          "16x16",
          "32x32",
          "180x180",
          "192x192",
          "512x512",
          "PWA",
          "Web-App-Manifest",
          "manifest.json",
          "maskable",
          "maskierbar",
          "Android",
          "Homescreen",
          "Startbildschirm",
          "Apple-Touch-Icon",
          "Touch-Icon",
          "Favicon erzeugen",
          "Browser-Tab",
          "Tab-Symbol",
          "PNG",
          "ICO",
          "Windows",
          "Programmsymbol",
          "Desktop-Verknüpfung"
        ],
        "tags": [
          "#icon",
          "#favicon",
          "#pwa"
        ]
      },
      "en": {
        "title": "Icon generator",
        "summary": "Creates favicon and icon sets from one image.",
        "description": "Turns one image into a complete set of icons: favicon, PWA icons, Apple touch icon and a maskable variant – entirely on your device.",
        "terms": [
          "icon",
          "icons",
          "favicon",
          "favicon.ico",
          "app icon",
          "website icon",
          "icon set",
          "icon sizes",
          "sizes",
          "16x16",
          "32x32",
          "180x180",
          "192x192",
          "512x512",
          "pwa",
          "web app manifest",
          "manifest.json",
          "maskable",
          "android",
          "homescreen",
          "home screen",
          "apple touch icon",
          "touch icon",
          "create favicon",
          "browser tab",
          "tab icon",
          "png",
          "ico",
          "windows",
          "program icon",
          "desktop shortcut"
        ],
        "tags": [
          "#icon",
          "#favicon",
          "#pwa"
        ]
      }
    }
  },
  {
    "id": "image-watermark",
    "route": "/tools/image-watermark",
    "icon": "/tools/image-watermark.svg",
    "category": "image",
    "suiteIds": [
      "image"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [
      "image/jpeg",
      "image/png",
      "image/webp"
    ],
    "output": [
      "image/jpeg",
      "image/png",
      "image/webp"
    ],
    "auxiliary": [
      {
        "role": "logo",
        "mimeTypes": [
          "image/png",
          "image/jpeg",
          "image/webp"
        ]
      }
    ],
    "locales": {
      "de": {
        "title": "Wasserzeichen",
        "summary": "Setzt Text oder Logo als Wasserzeichen auf ein Bild.",
        "description": "Setzt Text oder ein Logo als Wasserzeichen auf ein Bild – Position, Größe, Deckkraft, Drehung und Kachelmuster einstellbar, vollständig auf deinem Gerät.",
        "terms": [
          "wasserzeichen",
          "wasserzeichen einfügen",
          "bild wasserzeichen",
          "foto wasserzeichen",
          "copyright",
          "copyright-vermerk",
          "urheber",
          "urheberrecht",
          "schützen",
          "bildschutz",
          "fotorechte",
          "nachweis",
          "quelle",
          "quelle angeben",
          "text einfügen",
          "text auf bild",
          "logo einfügen",
          "logo auf bild",
          "branding",
          "marke",
          "firmenlogo",
          "deckkraft",
          "transparenz",
          "halbtransparent",
          "position",
          "platzierung",
          "ecke",
          "kacheln",
          "kachelmuster",
          "wiederholen",
          "muster",
          "diagonal",
          "drehen",
          "drehung",
          "bild",
          "foto",
          "jpeg",
          "png",
          "webp",
          "verkaufen",
          "exposé",
          "expose"
        ],
        "tags": [
          "#wasserzeichen",
          "#bilder",
          "#urheber"
        ]
      },
      "en": {
        "title": "Watermark",
        "summary": "Adds text or a logo as a watermark to an image.",
        "description": "Adds text or a logo as a watermark to an image – position, size, opacity, rotation and tiling are adjustable, entirely on your device.",
        "terms": [
          "watermark",
          "add watermark",
          "image watermark",
          "photo watermark",
          "copyright",
          "copyright notice",
          "attribution",
          "protect",
          "protect images",
          "image rights",
          "proof",
          "source",
          "credit",
          "credit line",
          "add text",
          "text on image",
          "add logo",
          "logo on image",
          "branding",
          "brand",
          "company logo",
          "opacity",
          "transparency",
          "semi transparent",
          "position",
          "placement",
          "corner",
          "bottom right",
          "tile",
          "tiled pattern",
          "pattern",
          "repeat",
          "diagonal",
          "rotate",
          "rotation",
          "image",
          "photo",
          "jpeg",
          "png",
          "webp",
          "for sale",
          "listing"
        ],
        "tags": [
          "#watermark",
          "#images",
          "#copyright"
        ]
      }
    }
  },
  {
    "id": "color-tools",
    "route": "/tools/color-tools",
    "icon": "/tools/color-tools.svg",
    "category": "image",
    "suiteIds": [
      "image"
    ],
    "executionMode": "local",
    "resourceClass": "universal",
    "worksOffline": true,
    "input": [
      "image/jpeg",
      "image/png",
      "image/webp"
    ],
    "output": [],
    "auxiliary": [],
    "locales": {
      "de": {
        "title": "Farbwerkzeuge",
        "summary": "Rechnet Farben um, prüft Kontrast und zieht Paletten aus Bildern.",
        "description": "Rechnet Farben zwischen HEX, RGB, HSL und LAB um, prüft den Kontrast nach WCAG, zieht die Palette aus einem Bild und zeigt, wie Farben bei Farbsehschwäche wirken – vollständig auf deinem Gerät.",
        "terms": [
          "farbe",
          "farben",
          "farbwerkzeug",
          "farbumrechnung",
          "umrechnen",
          "hex",
          "rgb",
          "hsl",
          "lab",
          "hex zu rgb",
          "rgb zu hex",
          "farbwert",
          "farbcode",
          "farbpipette",
          "pipette",
          "color picker",
          "palette",
          "farbpalette",
          "dominante farben",
          "farben aus bild",
          "farbkontrast",
          "kontrast",
          "wcag",
          "kontrastverhältnis",
          "kontrastverhaeltnis",
          "barrierefreiheit",
          "lesbarkeit",
          "text auf farbe",
          "farbsehschwäche",
          "farbsehschwaeche",
          "farbenblind",
          "protanopie",
          "deuteranopie",
          "tritanopie",
          "simulation",
          "design",
          "tokens",
          "websitedesign"
        ],
        "tags": [
          "#farbe",
          "#farben",
          "#barrierefreiheit"
        ]
      },
      "en": {
        "title": "Colour tools",
        "summary": "Converts colours, checks contrast and pulls palettes from images.",
        "description": "Converts colours between HEX, RGB, HSL and LAB, checks WCAG contrast, pulls the palette out of an image and shows how colours appear with colour vision deficiency – entirely on your device.",
        "terms": [
          "color",
          "colors",
          "colour",
          "colours",
          "color tool",
          "color converter",
          "convert",
          "hex",
          "rgb",
          "hsl",
          "lab",
          "hex to rgb",
          "rgb to hex",
          "color value",
          "color code",
          "color picker",
          "eyedropper",
          "palette",
          "color palette",
          "dominant colors",
          "colors from image",
          "color contrast",
          "contrast",
          "wcag",
          "contrast ratio",
          "accessibility",
          "readability",
          "text on color",
          "color blindness",
          "color vision deficiency",
          "protanopia",
          "deuteranopia",
          "tritanopia",
          "simulation",
          "design",
          "tokens",
          "web design"
        ],
        "tags": [
          "#color",
          "#colours",
          "#accessibility"
        ]
      }
    }
  },
  {
    "id": "pdf-merge",
    "route": "/tools/pdf-merge",
    "icon": "/tools/pdf-merge.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": [],
    "locales": {
      "de": {
        "title": "PDFs zusammenführen",
        "summary": "Verbindet mehrere PDFs in einer festgelegten Reihenfolge.",
        "description": "Verbindet mehrere PDF-Dokumente in frei gewählter Reihenfolge – lokal und ohne Upload.",
        "terms": [
          "PDF zusammenführen",
          "PDF verbinden",
          "PDF kombinieren",
          "PDF anhängen",
          "Dokumente zusammenfügen",
          "mehrere PDFs",
          "eine PDF",
          "Merge PDF",
          "PDF merger",
          "Seiten verbinden",
          "Dateien verbinden",
          "Sammeldokument",
          "Unterlagen bündeln",
          "Reihenfolge ändern"
        ],
        "tags": [
          "#pdf",
          "#zusammenführen",
          "#verbinden"
        ]
      },
      "en": {
        "title": "Merge PDFs",
        "summary": "Combines multiple PDFs in a chosen order.",
        "description": "Combines multiple PDF documents in your chosen order – locally and without uploads.",
        "terms": [
          "merge PDF",
          "combine PDF",
          "join PDF",
          "append PDF",
          "multiple PDFs",
          "one PDF",
          "merge documents",
          "combine documents",
          "join files",
          "page order",
          "bundle documents",
          "collate PDF",
          "PDF merger",
          "reorder documents"
        ],
        "tags": [
          "#pdf",
          "#merge",
          "#combine"
        ]
      }
    }
  },
  {
    "id": "pdf-split",
    "route": "/tools/pdf-split",
    "icon": "/tools/pdf-split.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": [],
    "locales": {
      "de": {
        "title": "PDF teilen",
        "summary": "Teilt PDFs in Seiten oder ausgewählte Bereiche.",
        "description": "Extrahiert einzelne Seiten oder frei festgelegte Seitengruppen aus einer PDF – vollständig lokal.",
        "terms": [
          "PDF teilen",
          "PDF trennen",
          "Seiten extrahieren",
          "Seiten entnehmen",
          "PDF aufteilen",
          "einzelne Seiten",
          "Seitenbereich",
          "Bereich exportieren",
          "Dokument zerlegen",
          "Split PDF",
          "PDF splitter",
          "Seiten speichern",
          "Seite herauslösen"
        ],
        "tags": [
          "#pdf",
          "#teilen",
          "#extrahieren"
        ]
      },
      "en": {
        "title": "Split PDF",
        "summary": "Splits PDFs into pages or selected ranges.",
        "description": "Extracts individual pages or custom page groups from a PDF – entirely on your device.",
        "terms": [
          "split PDF",
          "separate PDF",
          "extract pages",
          "remove pages",
          "page range",
          "export pages",
          "individual pages",
          "divide document",
          "PDF splitter",
          "save page",
          "break apart PDF",
          "selected pages"
        ],
        "tags": [
          "#pdf",
          "#split",
          "#extract"
        ]
      }
    }
  },
  {
    "id": "pdf-organize",
    "route": "/tools/pdf-organize",
    "icon": "/tools/pdf-organize.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": [],
    "locales": {
      "de": {
        "title": "PDF-Seiten organisieren",
        "summary": "Sortiert, dreht, dupliziert und löscht PDF-Seiten.",
        "description": "Sortiert, dreht, dupliziert und entfernt PDF-Seiten – mit lokaler Vorschau.",
        "terms": [
          "PDF Seiten sortieren",
          "Seiten organisieren",
          "Seiten drehen",
          "PDF drehen",
          "Seiten löschen",
          "Seiten entfernen",
          "Seite duplizieren",
          "Reihenfolge ändern",
          "PDF umordnen",
          "PDF neu ordnen",
          "rotate PDF",
          "reorder PDF",
          "delete pages",
          "page organizer"
        ],
        "tags": [
          "#pdf",
          "#seiten",
          "#sortieren"
        ]
      },
      "en": {
        "title": "Organize PDF pages",
        "summary": "Reorders, rotates, duplicates and deletes PDF pages.",
        "description": "Reorders, rotates, duplicates and removes PDF pages with a local preview.",
        "terms": [
          "organize PDF pages",
          "reorder PDF",
          "sort pages",
          "rotate PDF",
          "rotate pages",
          "delete pages",
          "remove pages",
          "duplicate page",
          "change page order",
          "page organizer",
          "rearrange PDF"
        ],
        "tags": [
          "#pdf",
          "#pages",
          "#organize"
        ]
      }
    }
  },
  {
    "id": "images-to-pdf",
    "route": "/tools/images-to-pdf",
    "icon": "/tools/images-to-pdf.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [
      "image/jpeg",
      "image/png"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": [],
    "locales": {
      "de": {
        "title": "Bilder zu PDF",
        "summary": "Verwandelt geordnete JPEG- und PNG-Bilder in ein PDF.",
        "description": "Erstellt aus JPEG- und PNG-Bildern ein PDF mit kontrollierter Reihenfolge, Seitengröße und Einpassung – vollständig lokal.",
        "terms": [
          "Bilder zu PDF",
          "Fotos zu PDF",
          "JPG zu PDF",
          "JPEG zu PDF",
          "PNG zu PDF",
          "Bilddateien verbinden",
          "Fotodokument",
          "Scan zu PDF",
          "Seitenformat A4",
          "Letter PDF",
          "Image to PDF",
          "Photo to PDF"
        ],
        "tags": [
          "#pdf",
          "#bilder",
          "#konvertieren"
        ]
      },
      "en": {
        "title": "Images to PDF",
        "summary": "Turns ordered JPEG and PNG images into one PDF.",
        "description": "Creates a PDF from JPEG and PNG images with controlled order, page size and fitting – entirely on your device.",
        "terms": [
          "images to PDF",
          "photos to PDF",
          "JPG to PDF",
          "JPEG to PDF",
          "PNG to PDF",
          "combine image files",
          "photo document",
          "scan to PDF",
          "A4 page size",
          "Letter PDF",
          "Bilder zu PDF",
          "Fotos zu PDF"
        ],
        "tags": [
          "#pdf",
          "#images",
          "#convert"
        ]
      }
    }
  },
  {
    "id": "pdf-to-images",
    "route": "/tools/pdf-to-images",
    "icon": "/tools/pdf-to-images.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "heavy",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "image/png",
      "image/jpeg"
    ],
    "auxiliary": [],
    "locales": {
      "de": {
        "title": "PDF zu Bildern",
        "summary": "Exportiert PDF-Seiten als PNG- oder JPEG-Bilder.",
        "description": "Rendert ausgewählte PDF-Seiten als PNG oder JPEG mit einstellbarer Auflösung und Hintergrundfarbe – vollständig lokal.",
        "terms": [
          "PDF zu Bild",
          "PDF zu PNG",
          "PDF zu JPG",
          "PDF zu JPEG",
          "Seiten exportieren",
          "PDF rendern",
          "DPI",
          "Auflösung",
          "PDF Bildkonverter",
          "PDF Seiten als Foto",
          "PDF to image",
          "PDF converter"
        ],
        "tags": [
          "#pdf",
          "#bilder",
          "#exportieren"
        ]
      },
      "en": {
        "title": "PDF to images",
        "summary": "Exports PDF pages as PNG or JPEG images.",
        "description": "Renders selected PDF pages as PNG or JPEG with adjustable resolution and background colour – entirely on your device.",
        "terms": [
          "PDF to image",
          "PDF to PNG",
          "PDF to JPG",
          "PDF to JPEG",
          "export pages",
          "render PDF",
          "DPI",
          "resolution",
          "PDF image converter",
          "PDF pages as photos",
          "PDF zu Bild",
          "PDF Konverter"
        ],
        "tags": [
          "#pdf",
          "#images",
          "#export"
        ]
      }
    }
  },
  {
    "id": "pdf-watermark",
    "route": "/tools/pdf-watermark",
    "icon": "/tools/pdf-watermark.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": [],
    "locales": {
      "de": {
        "title": "PDF-Wasserzeichen",
        "summary": "Fügt Text als einzelnes oder wiederholtes PDF-Wasserzeichen ein.",
        "description": "Setzt ein einstellbares Text-Wasserzeichen auf ausgewählte PDF-Seiten – lokal und ohne Upload.",
        "terms": [
          "PDF Wasserzeichen",
          "Wasserzeichen PDF",
          "Copyright PDF",
          "Text auf PDF",
          "vertraulich",
          "Entwurf",
          "Stempel",
          "Seiten markieren",
          "wiederholen",
          "kacheln",
          "Deckkraft",
          "Drehung"
        ],
        "tags": [
          "#pdf",
          "#wasserzeichen",
          "#dokument"
        ]
      },
      "en": {
        "title": "PDF watermark",
        "summary": "Adds text as a single or repeated PDF watermark.",
        "description": "Adds an adjustable text watermark to selected PDF pages – locally and without uploads.",
        "terms": [
          "PDF watermark",
          "watermark PDF",
          "copyright PDF",
          "text on PDF",
          "confidential",
          "draft",
          "stamp",
          "mark pages",
          "repeat",
          "tile",
          "opacity",
          "rotation"
        ],
        "tags": [
          "#pdf",
          "#watermark",
          "#document"
        ]
      }
    }
  },
  {
    "id": "pdf-page-numbers",
    "route": "/tools/pdf-page-numbers",
    "icon": "/tools/pdf-page-numbers.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": [],
    "locales": {
      "de": {
        "title": "PDF-Seitenzahlen",
        "summary": "Fügt frei formatierbare Seitenzahlen in PDFs ein.",
        "description": "Nummeriert ausgewählte PDF-Seiten mit Startwert, Format, Präfix und Suffix – vollständig lokal.",
        "terms": [
          "PDF Seitenzahlen",
          "PDF nummerieren",
          "Seiten nummerieren",
          "Seitennummer",
          "Fußzeile",
          "Kopfzeile",
          "Startnummer",
          "Seite von",
          "Präfix",
          "Suffix"
        ],
        "tags": [
          "#pdf",
          "#seitenzahlen",
          "#nummerieren"
        ]
      },
      "en": {
        "title": "PDF page numbers",
        "summary": "Adds freely formatted page numbers to PDFs.",
        "description": "Numbers selected PDF pages with a start value, format, prefix and suffix – entirely on your device.",
        "terms": [
          "PDF page numbers",
          "number PDF",
          "number pages",
          "page number",
          "footer",
          "header",
          "start number",
          "page of",
          "prefix",
          "suffix",
          "PDF Seitenzahlen"
        ],
        "tags": [
          "#pdf",
          "#page-numbers",
          "#number"
        ]
      }
    }
  },
  {
    "id": "pdf-visible-signature",
    "route": "/tools/pdf-visible-signature",
    "icon": "/tools/pdf-visible-signature.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "standard",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": [
      {
        "role": "signature",
        "mimeTypes": [
          "image/png",
          "image/jpeg"
        ]
      }
    ],
    "locales": {
      "de": {
        "title": "PDF sichtbar unterschreiben",
        "summary": "Platziert eine sichtbare elektronische Unterschrift in einer PDF.",
        "description": "Platziert ein Unterschriftenbild sichtbar auf einer PDF-Seite – lokal und klar getrennt von einer Zertifikatssignatur.",
        "terms": [
          "PDF unterschreiben",
          "Unterschrift PDF",
          "Signatur einfügen",
          "Unterschriftenbild",
          "PNG Unterschrift",
          "sichtbar signieren",
          "elektronische Unterschrift",
          "Datum",
          "platzieren"
        ],
        "tags": [
          "#pdf",
          "#unterschrift",
          "#signatur"
        ]
      },
      "en": {
        "title": "Visibly sign PDF",
        "summary": "Places a visible electronic signature in a PDF.",
        "description": "Places a signature image visibly on one PDF page – locally and clearly separate from a certificate signature.",
        "terms": [
          "sign PDF",
          "PDF signature",
          "add signature",
          "signature image",
          "PNG signature",
          "visible signature",
          "electronic signature",
          "date",
          "place signature",
          "PDF unterschreiben"
        ],
        "tags": [
          "#pdf",
          "#signature",
          "#sign"
        ]
      }
    }
  },
  {
    "id": "pdf-form-fill",
    "route": "/tools/pdf-form-fill",
    "icon": "/tools/pdf-form-fill.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "heavy",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": [],
    "locales": {
      "de": {
        "title": "PDF-Formular ausfüllen",
        "summary": "Füllt Textfelder, Auswahlfelder, Checkboxen und Optionsgruppen in PDFs aus.",
        "description": "Liest und füllt AcroForm-Felder lokal aus; XFA wird erkannt und klar als nicht unterstützt gekennzeichnet.",
        "terms": [
          "PDF Formular ausfüllen",
          "AcroForm",
          "PDF Felder",
          "Textfeld",
          "Checkbox",
          "Auswahlfeld",
          "Optionsfeld",
          "Formular speichern",
          "Formular einbetten",
          "XFA"
        ],
        "tags": [
          "#pdf",
          "#formular",
          "#ausfüllen"
        ]
      },
      "en": {
        "title": "Fill PDF form",
        "summary": "Fills text, choice, checkbox and radio fields in PDFs.",
        "description": "Reads and fills AcroForm fields locally; XFA is detected and clearly marked as unsupported.",
        "terms": [
          "fill PDF form",
          "AcroForm",
          "PDF fields",
          "text field",
          "checkbox",
          "choice field",
          "radio button",
          "save form",
          "flatten form",
          "XFA",
          "PDF Formular"
        ],
        "tags": [
          "#pdf",
          "#form",
          "#fill"
        ]
      }
    }
  },
  {
    "id": "pdf-annotate",
    "route": "/tools/pdf-annotate",
    "icon": "/tools/pdf-annotate.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "heavy",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": [],
    "locales": {
      "de": {
        "title": "PDF kommentieren und markieren",
        "summary": "Erstellt und entfernt standardisierte PDF-Annotationen.",
        "description": "Fügt echte PDF-Notizen, Markierungen, Formen, Linien und Freihand-Anmerkungen lokal hinzu.",
        "terms": [
          "PDF kommentieren",
          "PDF markieren",
          "Notiz PDF",
          "Hervorheben",
          "Unterstreichen",
          "Durchstreichen",
          "Freihand",
          "Rechteck",
          "Kreis",
          "Linie",
          "Annotation löschen"
        ],
        "tags": [
          "#pdf",
          "#kommentar",
          "#annotation"
        ]
      },
      "en": {
        "title": "Comment and mark up PDF",
        "summary": "Creates and removes standard PDF annotations.",
        "description": "Adds genuine PDF notes, markup, shapes, lines and ink annotations locally.",
        "terms": [
          "comment PDF",
          "mark up PDF",
          "PDF note",
          "highlight",
          "underline",
          "strike out",
          "ink",
          "rectangle",
          "circle",
          "line",
          "delete annotation",
          "PDF kommentieren"
        ],
        "tags": [
          "#pdf",
          "#comment",
          "#annotation"
        ]
      }
    }
  },
  {
    "id": "pdf-security",
    "route": "/tools/pdf-security",
    "icon": "/tools/pdf-security.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "heavy",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": [],
    "locales": {
      "de": {
        "title": "PDF schützen und entsperren",
        "summary": "Verschlüsselt PDFs mit AES-256 und entschlüsselt sie mit dem gültigen Passwort.",
        "description": "Schützt PDFs lokal mit AES-256 oder entfernt den Schutz mit einem gültigen Passwort.",
        "terms": [
          "PDF schützen",
          "PDF Passwort",
          "PDF verschlüsseln",
          "AES-256",
          "PDF entsperren",
          "PDF entschlüsseln",
          "Besitzerpasswort",
          "Berechtigungen"
        ],
        "tags": [
          "#pdf",
          "#sicherheit",
          "#passwort"
        ]
      },
      "en": {
        "title": "Protect and unlock PDF",
        "summary": "Encrypts PDFs with AES-256 and decrypts them with the valid password.",
        "description": "Protects PDFs locally with AES-256 or removes protection using a valid password.",
        "terms": [
          "protect PDF",
          "PDF password",
          "encrypt PDF",
          "AES-256",
          "unlock PDF",
          "decrypt PDF",
          "owner password",
          "permissions",
          "PDF schützen"
        ],
        "tags": [
          "#pdf",
          "#security",
          "#password"
        ]
      }
    }
  },
  {
    "id": "pdf-compress",
    "route": "/tools/pdf-compress",
    "icon": "/tools/pdf-compress.svg",
    "category": "pdf",
    "suiteIds": [
      "pdf"
    ],
    "executionMode": "local",
    "resourceClass": "heavy",
    "worksOffline": true,
    "input": [
      "application/pdf"
    ],
    "output": [
      "application/pdf"
    ],
    "auxiliary": [],
    "locales": {
      "de": {
        "title": "PDF komprimieren",
        "summary": "Verkleinert PDFs strukturell verlustfrei oder mit optionaler Bildkompression.",
        "description": "Optimiert PDF-Strukturen lokal und bietet wahlweise eine klar gekennzeichnete Bildkompression.",
        "terms": [
          "PDF komprimieren",
          "PDF verkleinern",
          "PDF optimieren",
          "PDF Dateigröße",
          "QPDF",
          "verlustfrei",
          "Bilder komprimieren"
        ],
        "tags": [
          "#pdf",
          "#komprimieren",
          "#optimieren"
        ]
      },
      "en": {
        "title": "Compress PDF",
        "summary": "Reduces PDFs structurally without loss or with optional image compression.",
        "description": "Optimises PDF structures locally and offers clearly labelled optional image compression.",
        "terms": [
          "compress PDF",
          "reduce PDF",
          "optimise PDF",
          "PDF file size",
          "QPDF",
          "lossless",
          "compress images",
          "PDF komprimieren"
        ],
        "tags": [
          "#pdf",
          "#compress",
          "#optimise"
        ]
      }
    }
  }
]
